# Generated by Django 5.1.1 on 2024-10-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
