# Generated by Django 5.1.1 on 2024-10-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_alter_team_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='team',
            new_name='Department',
        ),
    ]
