# Generated by Django 5.1.1 on 2024-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_rename_team_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('news_title', models.CharField(max_length=200)),
                ('news_image', models.ImageField(upload_to='media/')),
                ('description', models.TextField()),
                ('autor', models.CharField(max_length=20)),
                ('depart', models.CharField(max_length=200)),
            ],
        ),
    ]
