# Generated by Django 5.1.1 on 2024-10-10 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_email', models.EmailField(max_length=254)),
                ('book_date', models.DateField()),
                ('book_phn', models.CharField(max_length=20)),
                ('book_desc', models.TextField(max_length=500)),
                ('book_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthapp.department')),
            ],
        ),
    ]
